theme: minima
title: Sasha's page
description: _config Description
permalink: pretty
author: Sasha Monin
name: moninalexander
email: moninalexander@gmail.com


plugins:
  - jekyll-mermaid

mermaid:
  src: "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"


markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  fenced_code_blocks: true

header_pages:
  - physics/index.md
  - ML/index.md